env:
  browser: true
  es2021: true
  jest: true
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'
plugins: 
  - jest
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
